### PR TITLE
[DO NOT MERGE] Rebase check

### PR DESCRIPTION
**Pull request by jainvikas8**
Rebasing `tfm-v1.2-integration` on latest `master`. Raising pull for Travis run and review. This branch will be forced pushed to `tfm-v1.2-integration`

### CODE REVIEW

**Comment by LDong-Arm** [comment]
Will rebase after #74 is merged

**Comment by jainvikas8** [comment]
> Will rebase after #74 is merged

This PR is closed.

**Comment by LDong-Arm** [comment]
Had a brief look at each commit, it looks good.

**Comment by jainvikas8** [comment]
@evedon, please could look into this and force push?

**Comment by evedon** [comment]
I will review the commits in the next couple of hours. 
What tests did you run to validate the rebase?

**Comment by jainvikas8** [comment]
`python3 test_psa_target.py -t GNUARM -m ARM_MUSCA_B1` and CI builds works fine.

**Review by evedon — COMMENTED** [review]
Looks good

**Comment by LDong-Arm** [comment]
Closing this since the force push is done

**Pull request closed without merging**
