### PR TITLE
Added the -p option to choose the TF-m profile used for the build

### PR DESCRIPTION
**Pull request by Ame04**
- Useful to build for NUCLEO_L5
- Can be useful for other boards

### CODE REVIEW

**Review by jeromecoutant — APPROVED** [review]
@Patater

**Comment by Patater** [comment]
Please fix the black formatting issues identified by CI. Please also put the reasoning for the change into the commit description body (not only in the PR). Use imperative mood for commit message titles, too, please: "Add" instead of "Added". Thanks!

**Comment by Ame04** [comment]
@Patater commit is updated

**Comment by Patater** [comment]
Looks like there are still issues found by `black`. There seems to be some trailing whitespace, according to the log.

**Comment by Ame04** [comment]
@Patater commit is updated
i also changed the commit message as you asked me for the other PR.

**Review by Patater — APPROVED** [review]

**Pull request merged**
