### PR TITLE
Switch to `Black` formatting method

### PR DESCRIPTION
**Pull request by jainvikas8**
Use common formatter for python scripts:
* `psa_builder.py`
* `build_tfm.py`
* `build_psa_compliance.py`
* `test_psa_target.py`

### CODE REVIEW

**Comment by Patater** [comment]
Please remove `fix` from the commit message. We don't prefix with "commit type", but rather "which aspect or component of the repo we are changing".

**Comment by Patater** [comment]
We need an automated way to prevent regressions in style before we move forward with this change.

**Comment by jainvikas8** [comment]
Forced pushed:
* Address comments
* Rebased to resolve conflicts.

**Comment by rwalton-arm** [comment]
> We need an automated way to prevent regressions in style before we move forward with this change.

https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/pull/35 🙂

**Comment by jainvikas8** [comment]
Forced pushed to correct formatting.

**Comment by jainvikas8** [comment]
Tested with - `python3 test_psa_target.py -t GNUARM -m ARM_MUSCA_B1 -b` 
The above script executes all the scripts which are changed in this PR.

**Pull request merged**
